pipeline {
  agent any
  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'ref', value: '$.ref']
     ],

     causeString: 'Triggered on $ref',

    //  token: 'abc123',
    //  tokenCredentialId: '',

     printContributedVariables: true,
     printPostContent: true,

     silentResponse: false,

//      regexpFilterText: '$ref',
     regexpFilterExpression: 'refs/tags/.*'
    )
  }
  stages {
    stage('Some step') {
      steps {
        sh "echo $ref"
      }
    }
  }
}
